### ISSUE TITLE
Link to "Spock As a Drop In Replacement For Argparser" broken in docs

### ISSUE THREAD

**Issue by metaperl** [fidelity/spock#234]
**Describe the bug**
The Link to "Spock As a Drop In Replacement For Argparser" is broken in docs

**To Reproduce**
1. Go to https://fidelity.github.io/spock/Quick-Start
2. Scroll down to bottom of page
3. Click on "here" in the sentence See the docs/example [here](https://fidelity.github.io/spock/docs/ArgParser-Replacement/).

**Expected behavior**
Docs

**Actual Behavior**
```
Page Not Found
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
```

**Comment by ncilfone** [comment]
closed with #236
