### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by sidnarayanan** [fidelity/spock#5]
Allow command line arguments to define configuration parameters. These arguments should override anything defined in YAMLs.

**Comment by ncilfone** [comment]
#2 should be able to support this feature if Spock uses attrs as the backend (via .evolve)

**Comment by ncilfone** [comment]
@sidnarayanan #2 Should be in a good enough state to pull this forward... I can take a crack at it

**Comment by ncilfone** [comment]
@sidnarayanan 

79db232 should be all we need for this. Passes new tests for overrides.

**Comment by ncilfone** [comment]
#15 resolves
