### ISSUE TITLE
Remove config as a required argument

### ISSUE THREAD

**Issue by bkleyn** [fidelity/spock#61]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I do not always want to specify a value for the `--config` argument and in some cases would like to use spock similar to argparse, relying on the default values and specifying argument values only when needed.

**Describe alternatives you've considered**
I am overriding the values in the config file by adding them to explicitly as arguments, but would prefer to avoid this usage.

**Additional context**

**Comment by ncilfone** [comment]
@bkleyn Still on this... actually requires a bit of surgery as I had overlooked this usage pattern. Hopefully a PR this week.
